### ISSUE TITLE
Oh

### ISSUE THREAD

**Issue by Janmm14** [games647/Minecraft-Blocked-Servers#1]
Thanks for stealing the list from https://git.aperture.lol/projects/MOJANG/repos/blockedservers/browse/blockedservers.txt

Can you add in at least a link back?

**Comment by sleiss** [comment]
He already added a notice: http://puu.sh/oBHLB/7d33c92c16.png

He also seems to have found ftb.phanaticmc.com faster.

**Comment by Janmm14** [comment]
@ghacproductions The link you posted is error 403 now: http://ftb.phanaticmc.com/

**Comment by sleiss** [comment]
@Janmm14 already fixed it.
