### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ghost** [games647/Minecraft-Blocked-Servers#9]
I wonder, how do you crack these?

Also, I'm adding this list to http://wiki.vg/Mojang_API#Blocked_Servers Is that okay?
Here's what I want to add there:

``` html
=== Response ===
<pre>
27ae74becc8cd701b19f25d347faa71084f69acd
6f2520f8bd70a718c568ab5274c56bdbbfc14ef4
b13009db1e2fbe05465716f67c8d58b9c0503520
3e560742576af9413fca72e70f75d7ddc9416020
e3985eb936d66c9b07aa72c15358f92965b1194e
b140bec2347bfbe6dcae44aa876b9ba5fe66505b
c005ad34245a8f2105658da2d6d6e8545ef0f0de
11a2c115510bfa6cb56bbd18a7259a4420498fd5
75df09492c6c979e2db41116100093bb791b8433
c78697e385bfa58d6bd2a013f543cdfbdc297c4f
c645d6c6430db3069abd291ec13afebdb320714b
709a849e4e7a986c8165083dccb9857bcb04c67b
073ca448ef3d311218d7bd32d6307243ce22e7d0
33839f4006d6044a3a6675c593fada6a690bb64d
4d303ec6c914007f3214ce9184e1891e97af71de
266723d98e2cccb7b45c9364c7716efe4da00dfa
</pre>

All of the current hashes except one have been cracked. They are as follows:
<pre>
27ae74becc8cd701b19f25d347faa71084f69acd : *.arkhamnetwork.org
6f2520f8bd70a718c568ab5274c56bdbbfc14ef4 : *.minetime.com
b13009db1e2fbe05465716f67c8d58b9c0503520 : *.endercraft.com
3e560742576af9413fca72e70f75d7ddc9416020 : *.insanefactions.org
e3985eb936d66c9b07aa72c15358f92965b1194e : *.insanenetwork.org
b140bec2347bfbe6dcae44aa876b9ba5fe66505b : *.phoenixnexus.net
c005ad34245a8f2105658da2d6d6e8545ef0f0de : *.skygod.us
75df09492c6c979e2db41116100093bb791b8433 : *.timelesspvp.net
11a2c115510bfa6cb56bbd18a7259a4420498fd5 : *.slaughterhousepvp.com
c78697e385bfa58d6bd2a013f543cdfbdc297c4f : *.mineaqua.net
c645d6c6430db3069abd291ec13afebdb320714b : *.mineaqua.es
709a849e4e7a986c8165083dccb9857bcb04c67b : Not cracked yet.
073ca448ef3d311218d7bd32d6307243ce22e7d0 : *.diacraft.org
33839f4006d6044a3a6675c593fada6a690bb64d : *.diacraft.de
4d303ec6c914007f3214ce9184e1891e97af71de : *.menoxia.com
266723d98e2cccb7b45c9364c7716efe4da00dfa : *.styxnetwork.net
```

**Comment by TuxCoding** [comment]
> Also, I'm adding this list to http://wiki.vg/Mojang_API#Blocked_Servers Is that okay?

Yes of course

> I wonder, how do you crack these?

You could take a look at the Contribute.java file. 

Basically the server addresses are hashed with sha1. (i.e. mc.minecraft.com => a26733b5e81732074e883f96ff3154372e51fedb)

Nowadays wildcards will be used too.
*.minecraft.com => c2498d0431bdc7e1e0f6fce44dd82ded4c19d902
This will block every subdomain
Example:
mc.minecraft.com
abc.minecraft.com
123.minecraft 

For IPs the wildcards will be added at the end
123.123.123.*

will block everything for that star. Similar to the other example.

**How we can find the actual address?**
Try every addresses which is use for minecraft servers, hash it and test if it is in the list.

**Where I got these server addresses?** From minecraft server lists, twitter, forums (if they try to workaround the blocking by buying a new different domain).

I found out that the list is ordered (like line 4 + 5, 10 + 11, 13 + 14). So the last uncracked hash could be an address of mineaqua like an new ip or different domain.

**Comment by ghost** [comment]
Thanks! Now I understood.

**Comment by ghost** [comment]
> Update 4: All servers are found

Also, this line in description is false.

**Comment by TuxCoding** [comment]
Thanks for pointing that out. It was a bad idea to add it there.
